# Generated by Django 4.1.7 on 2023-03-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_solved',
            field=models.BooleanField(default=False),
        ),
    ]
