# Generated by Django 4.1.7 on 2023-04-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.TextField()),
                ('status', models.CharField(choices=[('resolved', 'Resolved'), ('in_progress', 'In Progress'), ('not_resolved', 'Not Resolved')], max_length=20)),
                ('notes', models.TextField()),
            ],
        ),
    ]
